### ISSUE TITLE
Name resolution issues

### ISSUE THREAD

**Issue by singold** [sn0b4ll/aria2-onion-downloader#18] opened 2024-02-11 13:40 UTC
I'm trying to download from an .onion site and have DNS issues.

First I got:
downloader_1  | 02/11 13:14:54 [ERROR] CUID#16 - Download aborted. URI=https://xxx.onion/
downloader_1  | Exception: [AbstractCommand.cc:351] errorCode=19 URI=https://xxx.onion/
downloader_1  |   -> [AbstractCommand.cc:789] errorCode=19 CUID#16 - Name resolution for xxx.onion failed:Domain name not found

I "fixed" that setting async dns to false

But now I get:
downloader_1  | 02/11 13:19:34 [ERROR] CUID#17 - Download aborted. URI=https://xxx.onion/
downloader_1  | Exception: [AbstractCommand.cc:351] errorCode=19 URI=https://xxx.onion/
downloader_1  |   -> [NameResolver.cc:58] errorCode=19 Failed to resolve the hostname xxx.onion, cause: Name does not resolve

I've read the README multiple times in case I've forgotten something, and also googled the error but couldn't find much.

Any pointers in the right direction would be greatly appreciated.

Thanks in advance

**Comment by sn0b4ll** [comment] 2024-02-21 14:53
Hey @singold,

is this only for one specific domain / have you tried other sides? Sorry, I have not encountered the error until now 😐

**Comment by sn0b4ll** [comment] 2024-02-27 07:27
Closing because if missing response.

**Closed as completed by sn0b4ll** 2024-02-27 07:27 UTC
Labels: in-investigation

**Comment by singold** [comment] 2024-02-27 17:01
Hi, sorry for my lack of response. I haven't seen the previous message.

I'll try with other domains to see if it is an issue with that domain and I'll let you know.

**Comment by pirhoo** [comment] 2024-10-30 10:31
I narrowed down the problem. It happens when you try to download a file through HTTPS but the website domain is not signed.

For instance, downloading this file works:

http://colincxvz44tojjdzbpesebml5pnyzl2g2qcy7ixhmghhkfqo64zmdyd.onion/assets/rss.svg

But this doesn't:

https://colincxvz44tojjdzbpesebml5pnyzl2g2qcy7ixhmghhkfqo64zmdyd.onion/assets/rss.svg

So the error "name do not resolve" is misleading. This can be a problem with websites that only answer to HTTPS requests without offering a valid certificate.

It's weird because the when we turn down certificate check (`check-certificate=false`), the error is still there. Maybe there is something to tweak in the v2ray config?

**Comment by reece394** [comment] 2025-04-16 18:50
Thanks @pirhoo for this reproducible link that made it easier to trace the issue. I managed to fix this. Turns out we weren't actually proxying https connections at all through the load balancer with aria2 only putting through http requests. Implemented this and loosened the restrictions on certificates so this should solve most issues in relation to this. Pull request will be up shortly.

**Comment by pirhoo** [comment] 2025-04-17 13:39
@reece394 thanks for troubleshooting this. I tried your changes and I can confirm it fixes the missing-certificate issue!
